---
dist: xenial
language: python
python: 3.7
services: docker

env:
  global:
    - IMAGE_NAME=dhsncats/code-gov-update
    - DOCKER_USER=jsf9k
    - secure: "j/i4XioToNCXLiQrEDchXdEJtCiFf6Yf50Kj9qLeFokGNrVdAR2r+G5\
fGb8lx/NgpI4z2wEojT4yH5k7s4sKAqnrm5pDOHsBC5Lgi+PnVLIyiQt2b2NbSY08eBHd7\
CBzjEWSKpmYfbDJdVzjZQtE0DpesrFuOk2SH+foNs4D9Mi0FN2klmISk02UcCGfJHiiryL\
/ht0tK/wQkLE/PSs9YtqV+DEcTZc3oXwsQ5itDUgaBbl6mBVs3sBwHm5SSNhZK1myQYMMp\
ZHYqJ5zw5EQ8qE0sObMuqpeGymwV+G0P8yk5voT9BCRLrlulCkNzjBcKJ+itiKPZY1imJ3\
RLqRzniFKzCvVWwXJTtFKBoAGvT29ZhgaGedsK4RVU2KcE+KVgbo+XqZyd0gDGXn1K+Tlc\
c/frPMaEHdkUBbz0nYu+6ETDF50kz8WBjuBAwGYPPOd0rnVTQFrLaNkz4AMKa3NTeXLobX\
l274Fr8xjgBYtc0pJXiNH+01xWn2xCNAtEXuL4HBoyIwM8oXK+di1IkzC2Q/ORBPZY1MSb\
34orRO0w01G3oswS/AX5OkSOAoWmesdR4YohAJ/QOIFgc3gdv8NxkVoYR7ea8Ro5XENdjG\
MHSnqTsiJ9QpDnzeNJEPd5oPucQWDwhX6b0Bn6R/s0ORRzJ8B0e4QofuzvjZ+XXifHA8="

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - travis_scripts/build_docker_image.sh

deploy:
  - provider: script
    script: travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
