---
version: '3.2'

secrets:
  scraper_config:
    file: secrets/scraper.json
  aws_config:
    file: secrets/aws_config

services:
  update:
    image: 'dhsncats/code-gov-update:0.0.2'
    secrets:
      - source: scraper_config
        target: scraper_config.json
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
