---
version: '3.7'

# This docker-compose file is used to build and test the container

secrets:
  aws_config:
    file: ./src/secrets/aws_config
  scraper_config:
    file: ./src/secrets/scraper.json

services:
  update:
    build:
      context: .
      dockerfile: Dockerfile
    image: cisagov/code-gov-update
    init: true
    secrets:
      - source: aws_config
        target: aws_config
      - source: scraper_config
        target: scraper_config.json
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
